# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Feriel Presswalla"                      # Your name
  description: "Feriel is a PhD pre-candidate at the Case Western Reserve University School of Medicine, in the Clinical Translational Science Program"   # A brief slogan (optional)
  image: img/Headshot.jpg
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
 
    
    # your sub-pages
    left:
      - text: "Education"
        href: education/index.qmd
      - text: "Research Experience"
        href: research experience/index.qmd
      - text: "Papers & Presentations"
        href: publications/index.qmd
      - text: "CV"
        href: cv/index.qmd
      - text: "Blog"
        href: blog/index.qmd
    
    # your social media handles
    right:
    
    - icon: linkedin
      href: https://www.linkedin.com/in/ferielpresswalla/
    - icon: mortarboard
      href: https://scholar.google.com/citations?hl=en&user=alq3y1cAAAAJ
    - icon: flower2
      href: https://orcid.org/0000-0001-7190-5622
    - icon: archive
      href: https://www.researchgate.net/profile/Feriel-Presswalla
    - icon: github
      href: https://github.com/ferielp/
    - icon: envelope
      href: "mailto:fxp124@case.edu"  
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2025 Feriel Presswalla CC </span>
    center: |
    right: |
      <span class="faux-block"><a href="- icon: github
        href: https://github.com/ferielp/"></a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true