# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Feriel Presswalla, BS"                                # Your name
  description: "Feriel is a PhD pre-candidate at the Case Western Reserve University School of Medicine, in the Clinical Translational Science Program"   # A brief slogan (optional)
  image: img/Headshot.jpg
  
  favicon: img/favicon.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/logo.png
    
    # your sub-pages
    left:
      - text: "Projects"
        href: projects/index.qmd
      - text: "Photography"
        href: photography/index.qmd
      - text: "CV"
        href: cv/index.qmd
    
    # your social media handles
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/ferielpresswalla/
      - icon: orcid
        href: https://orcid.org/0000-0001-7190-5622
      - icon: google scholar
        href: https://scholar.google.com/citations?hl=en&user=alq3y1cAAAAJ
      - icon: envelope
        aria-label: email
        href: "mailto:fxp124@case.edu"  
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2024 Feriel Presswalla CC </span>
    center: |
    right: |
      <span class="faux-block"><a href="https://github.com/marvinschmitt/quarto-website-template/">View source on GitHub</a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true