---
title: Blog
---

## How to be a (relatively) modern scientist

**March 24th, 2025**

This website started out as an assignment for a first-year statistics course, which unbeknownst to me has provided more in the way of mentorship and career guidance than several of my rotations. The course was structured with thought and care put towards building far-reaching research skills accessed through various statistical concepts (reproducibility in research: code and version management; communicating the facts of the data: designing and describing plots without introducing bias). The instructor’s hope, which I now share, is that this website will serve as the cornerstone for a continuing and flourishing online professional presence. In furtherance of this goal, we were also assigned to read Jeff Leek's book “[How to Be a Modern Scientist](https://leanpub.com/modernscientist).” Written in 2016, it has certainly aged in many ways. However, academia's traditions are deeply entrenched and many are still catching up to the idea of making research open source to those outside the ivory tower.

It is a proselytism urging academics to utilize the internet to cement the reproducibility of their data, open-source their methods and code, and critique each other in view of the public, connecting with laymen where they are and engaging their audience in entertaining ways. While I am used to scribbling notes in the margins of my books, I will take this opportunity to synthesize my scribbled notes into a review of the points Leek made that most caught my attention, with the view that perhaps, they will catch yours.

1.  How do pre-prints really work?\
    \
    While you wait for the paper you have submitted to a journal to go through the peer review process - don't wait. You can put it on your CV and share it on your platforms right away by letting arXiv (or biorXiv, as the case may be) host it. You cannot take it down once it is up there, but you can get immediate feedback and begin making modifications in anticipation of the reviewer comments you will likely as the the traditional process chugs along. Once you clean it up, you can submit your revised paper and keep it current with the published version.\
    One concern I had as I read Leek's thoughts on pre-prints was whether any journals had policies against accepting submissions that were already pre-prints, or allowing submissions under consideration to be posted as pre-prints. At the time of this blog post, posting of pre-prints is not considered prior publication for and will not jeopardize consideration at the following journals: Nature Portfolio, NEJM, PNAS, PLOS One. As always, it behooves the author to check each publisher's policy before making such weighty decisions.\

2.  What does a good peer review look like?\
    \
    Any major or minor issues you find should be listed in bullets, and prefaced by a summary in your words of what you perceive to be the most relevant takeaways of the paper. This helps the authors get a feel for whether the correct things were emphasized in their manuscript, and how well their core concepts were communicated.\
    Don't agree to be a reviewer if you cannot turn it around in 1-2 weeks. Don't write reams of prose. Don't ask for revisions if you don't plan on accepting the manuscript regardless of whether the authors make the changes you request. Do unto others...and all that.\
    BONUS: If a peer reviews a paper in the forest and no one sees them do it, did it happen? Get credit for your contributions to academic rigor by making a Publons profile and sending them the email in which you are thanked for your review. Even commenting on papers as a casual peer on PubMed Commons will get you credit.\

3.  Create literate programming habits

    Coming from a basic science background, I have a love-hate relationship with The Lab Notebook. It can make or break your sanity when you try to reproduce how you reasoned through various iterations of an experiment 3 years after you did it. I have learned to chronicle the process of my coding and analyses both for my future self and for colleagues I might need to present to, using Quarto and RMarkdown. Leek also suggest we become familiar with the Jupyter notebook platform, which is certainly on my to-do list. After learning how to use python, I suppose.
